import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavbarResizable } from "@/components/NavbarResizable";
import { ThemeProvider } from "@/libs/theme-provider";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} bg-black text-white max-w-[1600px] mx-auto antialiased`}
        >
      <ThemeProvider
      attribute={'class'}
      defaultTheme="dark"
      >
        <NavbarResizable/>
        <main>
        {children}
        </main>
        <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
